name: app_quanao
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.2
  http: ^0.13.4
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  crypto: ^3.0.3
  path: ^1.8.3
  logging: ^1.2.0
  shared_preferences: ^2.5.3
  bcrypt: ^1.1.3
  image_picker: ^1.1.2
  uuid: ^4.5.1
  firebase_core: ^2.0.0
  firebase_storage: ^11.0.0
  reorderables: ^0.6.0

  syncfusion_flutter_charts: ^25.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
